title: David Tan
author: David Tan
email: dctan16@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the best place to be

# social links
twitter_username: davidtan # DO NOT include the @ character, or else the build will fail!
github_username:  tancakes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
